### PR TITLE
Recruit/garrison fix

### PR DESCRIPTION
**Pull request by wriley**
Fixed indexes on some recruits
Don't charge player if suitable position not found for HMG/GMG

### CODE REVIEW

**Comment by Nifnat** [comment]
Github's stopped emailing me about this repo again so I've missed these pull requests, I'll hopefully find some time to look at these 
 and test them next week.

**Comment by wriley** [comment]
> Github's stopped emailing me about this repo again so I've missed these pull requests, I'll hopefully find some time to look at these
> and test them next week.

No worries, thanks for the mod of Overthrow

**Comment by Nifnat** [comment]
I'll update the steam workshop version with these changes in the next few days.

**Comment by wriley** [comment]
Cool, thanks for a fun mod

**Pull request merged**
